config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#welcome'
  get '/welcome', to: "pages#welcome"
  resources :simulations, only: [:index]
  resources :pages, only: [:index]
  resources :doc_lines, only: [:index]
  resources :documents, only: %i[index new show create edit update destroy], shallow: true do
    resources :doc_lines, only: [:show]
  end
  post 'downloads' ,to:'documents#downloads', as: :download_documents
  post 'prints' ,to:'documents#prints', as: :print_documents
end

app/views/shared/_avatar.html.erb
<div style="position:fixed; left: 11px; top:25px;z-index: 9999;">
  <%= link_to welcome_path do %>
    <%= image_tag "icon-logo.png", alt: "alttext", width: "57" %>
  <% end %>
</div>

  <div style="position:fixed; right: 10px; top:15px;">
    <% if user_signed_in? %>
        <% if current_user.photo.attachment.nil? %>
          <%= image_tag "avatar_manquant.png", class: "avatar-square dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= cl_image_tag current_user.photo.key, class: "avatar-square dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <p><%= link_to "Gérer votre profil", "#", class: "dropdown-item" %></p>
          <p><%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item", method: :delete %></p>
        </div>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
  </div>

app/views/shared/_cards_dash.html.erb
<div class="card-dash">
  <div class="card-dash-body">
    <div class="row align-items-center">
      <div class="col-sm-4 text-center">
        <%= image_tag(img) %>
      </div>
      <div class="col-sm-8">
        <p class="card-title m-0"><%= title %></p>
        <h4 class="card-text"><%= value %></h4>
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <button class="navbar-toggler" style="float:left;" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <% if user_signed_in? %>
      <ul class="m-0 pl-2">
        <li>
          <%= link_to welcome_path do%>
            <div class='nav-link d-flex align-items-center menu-item' style="position: relative;">
              <i class="fas fa-home"></i>
              <p class='bg-dark p-1 etiquette text-center' style="width: 100px;position: absolute;left: 30px;border-radius: 10px;font-size: 11px;">Accueil</p>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to documents_path do %>
            <div class='nav-link d-flex align-items-center menu-item my-2' style="position: relative;">
              <i class="fas fa-folder-open"></i>
              <p class='bg-dark p-1 etiquette text-center' style="width: 140px;position: absolute;left: 30px;border-radius: 10px;font-size: 11px;">Mes documents</p>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to doc_lines_path do %>
            <div class='nav-link d-flex align-items-center menu-item' style="position: relative;">
              <i class="fas fa-chart-bar"></i>
              <p class='bg-dark p-1 etiquette text-center' style="width: 150px;position: absolute;left: 30px;border-radius: 10px;font-size: 11px;">Mon tableau de bord</p>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to simulations_path do %>
            <div class='nav-link d-flex align-items-center menu-item mt-2' style="position: relative;">
              <i class="fas fa-calculator"></i>
              <p class='bg-dark p-1 etiquette text-center' style="width: 150px;position: absolute;left: 30px;border-radius: 10px;font-size: 11px;">Mes simulations</p>
            </div>
          <% end %>
        </li>
      </ul>
    <% else %>
      <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</nav>


  <div style="position: fixed;bottom:0;">
    <p class="text-white" style="padding-left: 10px;font-size: 12px;text-align: center;">  © 2020 - <br> Pass.Pro</p>
  </div>