config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#welcome'
  get '/welcome', to: "pages#welcome"
  resources :simulations, only: [:index]
  resources :pages, only: [:index]
  resources :doc_lines, only: [:index]
  resources :documents, only: %i[index new show create edit update destroy], shallow: true do
    resources :doc_lines, only: [:show]
  end
  post 'downloads' ,to:'documents#downloads', as: :download_documents
  post 'prints' ,to:'documents#prints', as: :print_documents
end

app/views/pages/home.html.erb
<div>
  <div><%= image_tag "billy.png", alt: "alttext", style:"width:90px; margin:1%;" %></div>
<div class="home-video-wrapper rounded">
  <%= video_tag "banner.mp4", controls:true, autoplay: true, loop: :loop, muted: :muted, poster:'poster_photo.png', class:'home_video' %>
  <div class="d-flex justify-content-end w-100" style="height: 90vh; width: 100vw; margin-top: 10px; margin-right:56vh;">
    <div class="form text-center" >
      <% if !current_user %>
        <%= simple_form_for(@user, url: session_path(@user)) do |f| %>
        <h1 class="text-primary">Administrophobe</h1>
        <p class="text-secondary" style="font-size:20px;">Simplifier le suivi de <br>votre vie professionnelle</p>
          <div class="form-inputs text-left">
            <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "email" },
                        class:"pb-3" %>
            <div class="mt-2"><%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "current-password" },
                        label: "Mot de passe" %>
            </div>
          </div>

          <div class="form-actions d-flex justify-content-center mt-4">
            <%= f.button :submit, "Je me connecte", class:"btn btn-secondary mr-1"%>
            <%= link_to "Je m'inscris", new_user_registration_path, class:"btn btn-success" %>
          </div>
        <% end %>

      <% end %>
      <% if current_user %>
        <%= link_to 'Je me déconnecte', destroy_user_session_path, method: :destroy, class: "btn btn-light"  %>
      <% end %>
    </div>
  </div>
</div>


<div class="container">

</div >
  <h3 class="text-center text-primary p-4 mb-4 pb-5">C'est tellement simple d'être connecté en toute confiance</h3>
</div>
</div>

<div class="d-flex justify-content-around w-100">
  <div class="row pb-5">
    <div class="col-sm">
      <div style="width: 18rem;" >
          <%= image_tag "hackermind.svg", class:"card-img-top ", style:"height:150px;" %>
          <div>
            <h4 class="text-center text-secondary mt-4">Stockage Sécurisé</h4>
            <p class="text-center">de mes données professionnelles</p>
          </div>
          </div>
    </div>

    <div class="col-sm">
            <div style="width: 18rem;">
          <%= image_tag "progress_data.svg", class:"card-img-top", style:"height:150px;", crop: :fill %>
          <div>
          <h4 class="text-center text-secondary mt-4">Tableau de Bord</h4>
          <p class="text-center">graphiques personnalisés</p>
          </div>
      </div>
    </div>

    <div class="col-sm">
            <div style="width: 18rem;">
          <%= image_tag "moment_to_relax.svg", class:"card-img-top", style:"height:150px;", crop: :fill %>
          <div>
          <h4 class="text-center text-secondary mt-4">Simulations</h4>
          <p class="text-center">retraite, impôts, formation</p>
          </div>
      </div>
    </div>

  </div>



</div>


<!-- FOOTER BABY -->
<div class="footer pt-2">
  <div><%= image_tag "billy.png", alt: "alttext", style:"width:70px; " %></div>
  <div class="footer-copyright text-white pt-2">
      <p> © monpasspro</p>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/pages/welcome.html.erb
  <div class="backgroundimage">
    <%= image_tag("pepouz.svg") %>
  </div>

<div class="container" >

  <div class="content-container">
      <h1 class="mt-5">Bonjour <%= current_user.first_name %>,</h1>
      <div class="w-100 text-center mt-5">
        <p class="ml-3" style="font-size:25px;">Que souhaitez-vous consulter aujourd'hui ?</p>
      </div>


      <div class="containerr mt-1 ml-5">
          <div class="cardd">
              <div class="face face1">
              <%= link_to(documents_path) do %>
                  <div class="content text-center">
                      <%= image_tag("hackermind.svg")%>
                      <h3>Mes bulletins de salaire</h3>
                  </div>
              </div>
              <% end %>
              <div class="face face2">
                <%= link_to(documents_path) do %>
                  <div class="content text-center">
                    <h5 class="text-white">Le coffre-fort sécurisé</h5>
                    <p class="title mb-3 text-white">Venez consulter tout l'historique de vos bulletins de paie.</p>
                    <p class="btn btn-warning p-2 w-100">Accédez aux documents</p>
                  </div>
              </div>
              <% end %>
          </div>
          <div class="cardd">
              <div class="face face1">
              <%= link_to(doc_lines_path) do %>
                  <div class="content text-center">
                      <%= image_tag("dashboard.svg")%>
                      <h3>Mon tableau de bord</h3>
                  </div>
              </div>
              <% end %>
              <div class="face face2">
              <%= link_to(doc_lines_path) do %>
                  <div class="content text-center">
                    <h5 class="text-white">Des graphiques personnalisés</h5>

                    <p class="title mb-3 text-white">Utile ! découvrez vos bulletins de salaire sous un nouvel angle.</p>

                    <p class="btn btn-warning p-2 w-100">Accédez aux graphiques</p>
                  </div>
              </div>
              <% end %>
          </div>
          <div class="cardd">
              <div class="face face1">
                <%= link_to(simulations_path) do %>
                  <div class="content">
                      <%= image_tag("simu.svg")%>
                      <h3>Simulations</h3>
                  </div>
              </div>
              <% end %>
              <div class="face face2">
                <%= link_to(simulations_path) do %>
                  <div class="content">
                    <h5 class="text-white text-center">Nos estimations</h5>
                    <p class="title mb-3 text-white">Des éléments de compréhension sur la valeur de votre retraite ou bien encore, de vos aides pôle emploi.</p>
                    <p class="btn btn-warning p-2 w-100">Accédez aux simulations</p>
                  </div>
              </div>
              <% end %>
          </div>
      </div>
  </div>
</div>

<style>


  .container{
  animation-duration: 2s;
  animation-name: slidein;
}


@keyframes slidein {
  from {
    margin-left: 100%;
    width: 300%;
  }

  to {
    margin-left: 25vh;
    width: 100%;
  }
}
</style>