config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#welcome'
  get '/welcome', to: "pages#welcome"
  resources :simulations, only: [:index]
  resources :pages, only: [:index]
  resources :doc_lines, only: [:index]
  resources :documents, only: %i[index new show create edit update destroy], shallow: true do
    resources :doc_lines, only: [:show]
  end
  post 'downloads' ,to:'documents#downloads', as: :download_documents
  post 'prints' ,to:'documents#prints', as: :print_documents
end

app/models/document.rb
require 'csv'

class Document < ApplicationRecord
  belongs_to :user
  validates :photo, presence: true
  has_many :doc_lines, inverse_of: :document, dependent: :destroy
  has_one_attached :photo

  accepts_nested_attributes_for :doc_lines,
                                allow_destroy: true

  include PgSearch::Model
    pg_search_scope :global_search,
      against: [ :name, :year, :month, :entreprise, :siret, :address ],
      using: {
        tsearch: { prefix: true }
      }

  def construction_hash(chemin_to_pdf)
    pdf_reader = PDF::Reader.new(chemin_to_pdf)
    page1 = pdf_reader.pages.first
    ocr = {}
    document_infos = {}
    doc_lines = {}
    page1.text.each_line do |li|
      doc_lines[:salaire_brut] = li.strip.split('  ').reject { |block| block == '' }[1].strip.gsub(" ","").to_f if li[/Salaire brut\b/]
      doc_lines[:impot_revenu] = li.strip.split('  ').reject { |block| block == '' }[3].strip.gsub(" ","").to_f if li[/Impôt sur le revenu\b/]
      doc_lines[:salaire_net_paye] = li.strip.split('  ').reject { |block| block == '' }[1].strip.gsub(" ","").to_f if li[/Net payé  [^:]/]
      doc_lines[:conge_n_1] = li.strip.split('  ').reject { |block| block == '' }[1].strip.gsub(" ","").to_f if li[/Solde\b/]
      doc_lines[:conge_n] = li.strip.split('  ').reject { |block| block == '' }[2].strip.gsub(" ","").to_f if li[/Solde\b/]
      doc_lines[:rtt] = li.strip.split('  ').reject { |block| block == '' }[3].strip.gsub(" ","").to_f if li[/Solde\b/]
      document_infos[:siret] = li.strip.split("  ").reject{ |test| test == ""}.select {|item| item.include?("Siret")}.join.split(" ")[2]  if (li[/Siret\b/])
      document_infos[:year] = li.strip.split("  ").reject{ |test| test == ""}.select {|item| item.include?("Période")}.join.split(" ")[3].to_i  if (li[/Période\b/])
      document_infos[:month] = li.strip.split("  ").reject{ |test| test == ""}.select {|item| item.include?("Période")}.join.split(" ")[2]  if (li[/Période\b/])
    end
    document_infos[:month] = traduire_mois(document_infos[:month])
    ocr[:doc_lines] = doc_lines
    ocr[:document_infos] = document_infos
    return ocr
  end

  def fabrique_le_name
    moiss = ['0', 'janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre']
    return self.name = "#{moiss[month].capitalize} #{year}"
  end

  private

    def traduire_mois(un_mois_en_string)
      moiss = ['0', 'janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre']
      moiss.each do |mois|
        return moiss.index(mois) if mois == un_mois_en_string.downcase.strip
      end
    end
end

app/controllers/documents_controller.rb
require 'open-uri'
require 'net/http'
class DocumentsController < ApplicationController

  def index

    @my_documents = Document.where(user: current_user)

    if params[:query].present?
      @documents = @my_documents.global_search(params[:query])
    else
      @documents = @my_documents
    end

    @documents_id = @my_documents.map{|doc| doc.id}
    @my_doclines = DocLine.select {|line| @documents_id.include? (line.document_id)}
  end

  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
  end

  def create
    # @document = Document.new(year: params_documents["year(1i)"], month: params_documents["month(2i)"], photo: params_documents[:photo] )
    @document = Document.new(photo: params_documents[:photo] )
    # @document.name = "#{Date::MONTHNAMES[params[:document]["month(2i)"].to_i]} #{params[:document]["year(1i)"]}"
    @document.user = current_user

    if @document.save
      redirect_to edit_document_path(@document)
    else
      render :new
    end
  end

  def edit

    @cat_hash = { "salaire_brut" => 0, "salaire_net_paye" => 1, "impot_revenu" => 2, "conge_n_1" => 3, "conge_n" => 4, "rtt" => 5 }
    @document = Document.find(params[:id])
    sleep(3)
    result = Cloudinary::Search.max_results(1).execute
    pdf = URI.open(result["resources"][0]["url"])
    ocr = {}
    ocr = @document.construction_hash(pdf)
    # ocr = {:salaire_brut=>"5083.33",
    #   :salaire_net_paye=>"3868.84",
    #   :impot_revenu=>"590.75",
    #   :conge_n_1=>"24.0",
    #   :conge_n=>"2.08",
    #   :rtt=>"2.88"
    #   :year=>2019
    #   :month=> (1..12)
    #   :siret=> "478558698525"

    @document.year = ocr[:document_infos][:year]
    @document.month = ocr[:document_infos][:month]
    @document.siret = ocr[:document_infos][:siret]
    url = "https://entreprise.data.gouv.fr/api/sirene/v3/etablissements/#{@document.siret}"
    document_serialized = open(url).read
    document_jason = JSON.parse(document_serialized)
    @document.entreprise = document_jason["etablissement"]["unite_legale"]["denomination"]
    @document.fabrique_le_name
    @document.save!

    ocr[:doc_lines].each do |key, value|
      dl = DocLine.new(category: key, amount: value.to_f)
      dl.data_entry_period = Date.new(@document.year, @document.month, 1)
      dl.document = @document
      dl.save!
    end
  end

  def update
    @document = Document.find(params[:id])
    if @document.update_attributes(params_documents)
      redirect_to documents_path, notice: 'Votre document a bien été sauvegardé'
    else
      render :edit
    end

  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_path
  end

  def downloads
    id = params[:downloads][:ids]
    ids = id[0].split(",")
    public_ids =[]
    ids.each { |id|
      public_ids << Document.find(id.to_i).photo.key
    }
    url = Cloudinary::Utils.download_archive_url(:public_ids => public_ids)

    redirect_to url
  end

  def prints
    id = params[:prints][:ids]
    ids = id[0].split(",")
    public_ids =[]
    results = []
    ids.each { |id|
      public_ids << Document.find(id.to_i).photo.key
    }
    public_ids.each { |id|

    results << Cloudinary::Search.expression(id).execute
    }
    pdf = CombinePDF.new
    results.each { |result|
       url  = result["resources"][0]["url"];
       page = CombinePDF.parse Net::HTTP.get_response(URI.parse(url)).body
       pdf << page
    }
    # pdf.save 'combined.pdf'
    # data = pdf.objects[1][:Pages][:referenced_object][:Kids][0][:referenced_object][:Contents][:referenced_object][:raw_stream_content]
    # Cloudinary::Uploader.upload("data:image/pdf;base64,#{data}")
  end


  private

  def params_documents
    # params.require(:document).permit(:photo, ["year(1i)"], ["month(2i)"], doc_lines_attributes: [:id, :name, :category, :amount] )
     params.require(:document).permit(:photo, doc_lines_attributes: [:id, :name, :category, :amount] )
  end


end

app/views/documents/_form.html.erb
<div class="container flex-column">
  <h1 class="my-3">Ajouter un bulletin de salaire</h1>
  <%= simple_form_for(Document.new) do |form| %>
    <%= form.input :photo, as: :file %>
    <div class="row">
      <div class="col">
        <%= form.input :year, as: :date,  discard_day: true, discard_month: true %>
      </div>
      <div class="col">
        <%= form.input :month, as: :date,  discard_day: true, discard_year: true  %>
      </div>
    </div>

    <%= form.button :submit, 'Ajouter' , class:'btn btn-primary w-100 mb-2'%>
  <% end %>
</div>

app/views/documents/_form_html.erb
<div class="modal fade" id="add_document" tabindex="-1" role="dialog" aria-labelledby="Ajouter un bulletin" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for (Document.new) do |form| %>
          <%= form.input :photo, as: :file %>
          <div class="row">
            <div class="col">
              <%= form.input :year, as: :date,  discard_day: true, discard_month: true %>
            </div>
            <div class="col">
              <%= form.input :month, as: :date,  discard_day: true, discard_year: true  %>
            </div>
          </div>

          <%= form.button :submit, 'Ajouter' , class:'btn btn-primary w-100 mb-2'%>
      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/documents/edit.html.erb
<div class="container">
  <h2 class="my-4">Confirmation de votre bulletin de salaire</h2>
  <div class="d-flex">
    <div class="w-75 pr-3">
      <%= cl_image_tag(@document.photo.key, format: :jpg, style: 'width: 90%;order: 1px solid #cbcbce5e; background:white;padding: 5%;') %>
    </div>
    <div class="text-center p-3 bg-white" style="border-radius: 20px; box-shadow: 0px 0px 10px #4d54e129;">
      <p style="font-size: 12px;">Merci de bien vérifier vos informations</p>
      <%= simple_form_for @document do |f| %>
        <%= f.submit 'Valider les informations', class: 'btn btn-success text-white w-100' %>
        <p class="my-3">Bulletin du mois de : <%= f.text_field :name, class: 'amount' %></p>
        <!-- ici un probleme d'ordre des doc_line ! a retravailler quentin 01/03 -->
        <% @document.doc_lines.sort_by { |dl| @cat_hash[dl.category] }.each do |doc_line| %>
          <%= f.fields_for :doc_lines, doc_line do |d| %>
            <p>
              <%= d.input :category, placeholder: doc_line.category.capitalize.gsub('_', ' '), input_html: {disabled: "disabled"}, label: false %>
              <%= d.input_field :amount, class: 'amount' %>
            </p>
          <% end %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

<style>


  .container{
  animation-duration: 2s;
  animation-name: slidein;
}


@keyframes slidein {
  from {
    margin-left: 100%;
    width: 300%;
  }

  to {
    margin-left: 25vh;
    width: 100%;
  }
}
</style>

app/views/documents/index.html.erb
<% groups = @documents.where(user: current_user).sort_by { |h| h.year }.reverse.group_by { |m| m.year } %>
<% salnet = @my_doclines.select{|line| line.category == 'salaire_net_paye'}.group_by{ |m| m.data_entry_period.year } %>

<div class="container">

  <div class="button-add">
    <i class="fas fa-plus", id="buttonModal", data-toggle="modal", aria-haspopup= "true", aria-expanded= "false", data-target="#add_document"></i>
  </div>

  <div class="modal fade" id="add_document" tabindex="-1" role="dialog" aria-labelledby="Ajouter un bulletin" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content text-center">
        <div class="d-flex justify-content-between align-items-center p-2">
          <button type="button" class="close w-100" data-dismiss="modal" aria-label="Close" style="text-align: right;">
            <span aria-hidden="true">╳</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <%= simple_form_for (Document.new) do |form| %>
            <div class="text-center">
              <h5 id="exampleModalLabel">Ajouter un bulletin</h5>
              <%= image_tag 'files.svg', alt: "alttext", style: 'width: 90%; padding: 10%;' %>
            </div>
            <div class="row my-2 mb-5">
<!--               <div class="col">
                <%= form.input :month, as: :date,  discard_day: true, discard_year: true, label: 'Mois'  %>
              </div>
              <div class="col">
                <%= form.input :year, as: :date,  discard_day: true, discard_month: true, label: 'Année' %>
              </div> -->
            </div>
            <%= form.input :photo, as: :file, label: false, class: 'btn btn-success', style: 'margin-top: 10px;' %>

            <%= form.button :submit, 'Ajouter' , class:'btn btn-primary w-100 mt-5', onclick:'cursor_wait();'%>
          <% end %>
          <div id="myModal" class="modal">

            <!-- Modal content -->
            <div class="modal-contenu" style="vertical-align: middle;">
              <p>✨</p>
              <h4 class="mt-4">Notre sorcier est en train d'extraire les données de votre fiche de paye  ...</h4>
              <%= image_tag "sorcier.gif", alt: "alttext", width: '580px' %>
              <p class='mx-5'style="font-size: 16px;">Merci de bien vouloir patienter quelques secondes afin que la magie s'opère</p>
              <p>✨</p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

  <h2 class="mt-4">Mes documents</h2>

  <div class="text-center">
    <%= form_tag documents_path, method: :get do %>
      <div class="d-flex justify-content-center align-items-center" style="position: relative;">
        <%= link_to 'Tout voir',  documents_path ,class:'all btn btn-warning m-1 text-white' %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Recherchez par année, mois, entreprise, etc...",
        autocomplete:"off"
        %>
        <%= button_tag type: 'submit', class: "bg-transparent p-1 text-warning loupe" do %>
          <i class="fa fa-search" aria-hidden="true"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class=' d-flex  justify-content-between align-items-start'>
    <button id='selection_multiple_doc' value=false class='btn btn-primary m-3 text-white'>Sélectionner</button>
    <div class='d-flex buttons-multi  mx-3 mt-4 invisible'>
      <%= simple_form_for(:downloads, url: download_documents_path) do |form| %>
        <%= form.input :ids, :as => :hidden, label:false, input_html: { multiple: true }, hidden:true %>
        <%= button_tag type: 'submit', class: "buttons-selections mr-2" do %>
          <i class="fa fa-download" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <%= simple_form_for(:prints, url: print_documents_path) do |form| %>
        <%= form.input :ids, :as => :hidden, label:false, input_html: { multiple: true }, hidden:true %>
        <%= button_tag type: 'submit', class: "buttons-selections disabled" do %>
          <i class="fa fa-print" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
  </div>

  <% groups.each do |group| %>
    <div class="section">
      <div class="entete d-flex justify-content-between align-items-center">
        <div class="m-0">
          <p class="m-0" style="font-size: 16px;">Année</p>
          <h2 class="text-info"><%= group[0] %></h2>
        </div>
        <div class="text-center">
          <% sal1 = 0 %>
          <% salnet[group[0]].each { |sal| sal1 +=  sal.amount } %>
          <p style="font-size: 11px;" class="m-0">Revenu annuel<strong class="ml-5"><%= sal1.round.to_s.reverse.gsub(/...(?=.)/,'\& ').reverse %> €</strong></p>
          <div class="progress">
            <div class="progress-bar bg-success m-0" role="progressbar" style="width: <%= (100 * group[1].size)/(12) %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <em class="w-100 text-center" style="font-size: 11px;"><%= group[1].size %> fiches sur 12</em>
        </div>
        <div>
          <%= link_to doc_lines_path do %>
            <div class="d-flex justify-content-between btn btn-primary">
              Mon tableau de bord
              <i class="ml-3 fas fa-chevron-right"></i>
            </div>
          <% end %>
        </div>
        </div>
      <div class="cards" style="position: relative;">
        <% i = 0 %>
        <% group[1].each do |document| %>
            <% i ++ 1 %>
            <div class="card" style="background-image: url('<%= cl_image_path(document.photo.key, format: :jpg) %>');">
              <div class="multi-button">
                <a href="mailto:<%= current_user.email %>" class="fas fa-share-alt"></a>
                <a href="<%= cl_image_path(document.photo.key) %>" class="fas fa-print" target="_blank"></a>
              </div>
              <div>
                <input type="checkbox" class="checkbox_card invisible " id="<%= document.id %>" disabled>
              </div>
              <div class="card-body">
                <%= link_to document_path(document), data: { toggle: 'modal', target: "#document-#{document.id}"} do %>
                  <div>
                    <h5 class="card-text pt-5 pb-4"><%= document.name %></h5>
                    <p><i class="pr-4 far fa-building"></i><%= document.entreprise %></p>
                    <p><i class="pr-4 fas fa-euro-sign"></i><%= DocLine.salaire_net_paye.find_by(document: document).amount.round(2) %></p>

                  </div>
                <% end %>
                <button class="button_multi invisible" type="button" value='<%= document.id %>' disabled ><i class="fas fa-check"></i></button>
              </div>
            </div>

             <!-- Modal -->
            <div class="modal fade" id="document-<%= document.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content preview">
                  <div class="modal-header" style="border: none;">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">╳</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <h1 class="text-center"><%= document.name %></h1>

                    <div class="d-flex" style="position:relative">
                      <div class="w-100 pr-2">
                        <%= cl_image_tag(document.photo.key , format: :jpg) %>
                      </div>
                      <div class="document-show p-2 m-0"  style="background-color: #F9D132; position: fixed; text-align: center;right: 40px;">
                        <h6>Informations</h6>
                        <p>
                          <strong>Salaire brut:</strong> <%= DocLine.salaire_brut.find_by(document: document).amount.round(2) %> €
                        </p>
                        <p>
                          <strong>Salaire net:</strong> <%= DocLine.salaire_net_paye.find_by(document: document).amount.round(2) %> €
                        </p>
                        <p>
                          <strong>Impot sur le revenu:</strong> <%= DocLine.impot_revenu.find_by(document: document).amount.round(2) %> €
                        </p>
                        <p>
                          <strong>Congés N-1:</strong> <%= DocLine.conge_n_1.find_by(document: document).amount.truncate %> jour(s)
                        </p>
                        <p>
                          <strong>Congés N:</strong> <%= DocLine.conge_n.find_by(document: document).amount.truncate %> jour(s)
                        </p>
                        <p>
                          <strong>RTT:</strong><%= DocLine.rtt.find_by(document: document).amount.truncate %> jour(s)
                        </p>
                      </div>

                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<style>
/* Modal Content/Box */
.modal-contenu {
  background-color: #fefefe;
  margin: 2% auto;
  padding: 20px;
  border: 1px solid #888;
  width: 45%;
  height: 685px;
  border-radius: 20px;
}

/* The Close Button */
.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}

</style>

<script>
  const cursor_wait = () => {
   setTimeout(document.body.style.cursor = 'wait', 4000);
   var modal = document.getElementById("myModal");
    modal.style.display = "block";
  }

</script>

app/views/documents/new.html.erb
  <div class="container">
    <div  class="text-center m-4">
      <h1>S'inscrire</h1>
    </div>
    <%= simple_form_for(Document.new) do |form| %>
      <%= form.input :photo, as: :file %>
      <div class="row">
        <div class="col">
          <%= form.input :year, as: :date,  discard_day: true, discard_month: true %>
        </div>
        <div class="col">
          <%= form.input :month, as: :date,  discard_day: true, discard_year: true  %>
        </div>
      </div>
      <%= form.button :submit, 'Ajouter' , class:'btn btn-primary w-100 mb-2', 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i>".html_safe %>
    <% end %>
  </div>

app/views/documents/show.html.erb
<h1 class="text-center mt-5  "><%= @document.name %></h1>

<div class="d-flex">
  <div class="document-show">
    <%= cl_image_tag(@document.photo.key , format: :jpg) %>

    <!-- <iframe src="<%#= cl_image_tag(@document.photo.key) %>" height="200" width="300"></iframe> -->
  </div>
  <div class="document-show">
    <p>
      <strong>Salaire brut:</strong> <%= DocLine.salaire_brut.find_by(document: @document).amount.round(2) %> €
    </p>
    <p>
      <strong>Salaire net:</strong> <%= DocLine.salaire_net_paye.find_by(document: @document).amount.round(2) %> €
    </p>
    <p>
      <strong>Impot sur le revenu:</strong> <%= DocLine.impot_revenu.find_by(document: @document).amount.round(2) %> €
    </p>
    <p>
      <strong>Congés N-1:</strong> <%= DocLine.conge_n_1.find_by(document: @document).amount.truncate %> jour(s)
    </p>
    <p>
      <strong>Congés N:</strong> <%= DocLine.conge_n.find_by(document: @document).amount.truncate %> jour(s)
    </p>
    <p>
      <strong>RTT:</strong><%= DocLine.rtt.find_by(document: @document).amount.truncate %> jour(s)
    </p>
  </div>

</div>